### ISSUE TITLE
Doesn't parse/honor Palette=lib in art.ini for RA2

### ISSUE THREAD

**Issue by ATHSE** [CnCNet/WorldAlteringEditor#1]
As title states, buildings with Palette=lib are still rendered using' unit*.pal

**Comment by ATHSE** [comment]
Addendum:

Normally all buildings are drawn using their theater specific version of unitxxx.pal, Palette=lib in their art.ini code instructs the game to load the theater specific variant of the libxxx.pal, ie. instead of unitsno.pal it loads libsno.pal, instead of uniturb.pal it loads liburb.pal.

Similar palette switching code exists in RA2's art.ini for other classes of objects:
- Units (.shp only) can have TerrainPalette=yes, which substitutes unitxxx.pal with isoxxx.pal
- Projectiles can have AnimPalette=yes, which substitutes unitxxx.pal with anim.pal
- Animations can have AltPalette=yes, which substitutes anim.pal with unitxxx.pal

PS. as much as it would seem logical, Palette=iso or Palette=unit does not work, it seems to be a specific exception made for the Statue of Liberty, not as a regular function. So Palette=lib should be treated as unitary, not as a command with a parameter.

**Comment by Rampastring** [comment]
@ATHSE This should be implemented now, can you confirm it works?

**Comment by ATHSE** [comment]
Crashes, the error suggests it might be choosing the name wrong, but hard to be certain. My mod includes a cache.mix with all the palettes including lib* and the rest seem to load fine.
![image](https://github.com/Rampastring/TSMapEditor/assets/96433329/3bf82f52-7a63-487f-ab75-1963957d0a7c)

**Comment by ATHSE** [comment]
It doesn't seem to matter which map I try to load now, it seems the presence of Palette=lib art in the mod, even without any buildings on the map, is enough to attempt to load the lib.x.pal ?

**Comment by Rampastring** [comment]
The extra dot in the filename should now be gone with https://github.com/Rampastring/TSMapEditor/commit/aadf024c6bf6a4ef65418f0212617ab733b6b118

**Comment by MortonPL** [comment]
> PS. as much as it would seem logical, Palette=iso or Palette=unit does not work, it seems to be a specific exception made for the Statue of Liberty, not as a regular function. So Palette=lib should be treated as unitary, not as a command with a parameter.

This was [fixed in Ares 0.1](https://ares-developers.github.io/Ares-docs/bugfixes/type2/custompalettes.html), so it should be treated as a configurable option.

> It doesn't seem to matter which map I try to load now, it seems the presence of Palette=lib art in the mod, even without any buildings on the map, is enough to attempt to load the lib.x.pal ?

This is correct, palettes are loaded on parsing BuildingType art rules.

It looks like this override functions correctly, I haven't had any BuildingType palette issues while loading vanilla Yuri's Revenge or mod maps.

**Comment by ATHSE** [comment]
The automatic loading of the palette (and thus crashing) was only an issue when the naming bug was introduced in the first attempt.

I wasn't aware Ares fixed the iso/unit values, but since it supports actual custom palettes, I figured Ares support would have to be a further PR.

**Comment by Rampastring** [comment]
Sounds like it's fixed then.
