### ISSUE TITLE
Please show all files, or allow the option in the File->Open dialog

### ISSUE THREAD

**Issue by ATHSE** [CnCNet/WorldAlteringEditor#10]
Currently there's no way to browse or select anything not *.map from within WAE, only during startup where it can be manually typed. At the very least there should be some consistency allowing a user to type in a name there too, but even better would be just to have a way to show all files, or allow us to define the file extensions we want to see.

Just a simple dropdown where we could see all the common map types, .map/.mpr/.yrm, and an additional "everything" choice is enough. There's probably no sense defining custom types in one of the configs to enable this, it should just show them all, but if additional mod-specific extensions are possible to add to the list, then maybe?

**Comment by ATHSE** [comment]
IF this feature is to be limited to types the game+mod in question supports, then a [SearchMaps] section can be added to filemanagerconfig.ini, wherein the various supported map extensions can be listed, and thus limit the open dialog to those extensions. The values could be defined as a numbered list as above 0=mpr, 1=yrm, OR just have one filemask per line like: *.mpr

The latter filemask option might be better however, if a modder wants to only see maps of their own making which follow a particular naming convention with a common prefix or suffix. e.g. mymod-*.yrm

In fact this could even be extended to cover the game mode variations. Game modes like MegaWealth in Westwood convention would be named with "mw" suffix for a map that also exists for normal battle modes. Thus the dropdown in the open dialog could then filter game modes as well as the map extension type using the filemasks.

**Comment by Rampastring** [comment]
This implementation, despite being hardcoded, is probably sufficient for now https://github.com/Rampastring/WorldAlteringEditor/commit/45d80674ed8fdc3354a508615101371d9aeec67a
