### ISSUE TITLE
AI Trigger's Secondary Teamtype is Replaced with a Duplicated Primary Teamtype When A Map is Loaded

### ISSUE THREAD

**Issue by krnyoshi** [CnCNet/WorldAlteringEditor#129]
As the title states, when you have an AI trigger that uses a different Secondary Teamtype, WAE will replace it with a Duplicated Primary Teamtype when loading the map.

Unsuspecting mappers may then accidentally save these overwritten teamtypes, and cause unintended results with their custom AI triggers.

Note: If they noticed, and fixed, the overwritten values, and then save the map, the corrected values will still be there.

**Comment by Rampastring** [comment]
Fixed by https://github.com/Rampastring/WorldAlteringEditor/commit/e8e04c9e6bcd9f8db52ddb4c6add088ca8bfa44d
