### ISSUE TITLE
WAE for YR cannot edit ScriptAction [DoThis] in the correct form

### ISSUE THREAD

**Issue by No-Fly-Zone** [CnCNet/WorldAlteringEditor#142]
In the TS, second parameter of ScriptAction `[DoThis]` (`11,X` in map) contains 25 value, while in RA2/YR it is 30/32.
Some values have added or changed their numbering in RA2/YR. But ScriptAction `[DoThis]` in WAE for YR, still maintaining the form in TS.

Values for RA2/YR update can be find in _Assign New Mission_ part at [https://modenc.renegadeprojects.com/ScriptTypes/ScriptActions]

**Comment by Rampastring** [comment]
This should now be fixed.
