### ISSUE TITLE
Ion Storm lighting preview should ignore color tint from light posts

### ISSUE THREAD

**Issue by Crimsonum** [CnCNet/WorldAlteringEditor#143]
In TS, the game ignores any color tint from light posts during Ion Storms, adjusting only the ambient brightness. However in WAE, when previewing the Ion Storm lighting, light posts emit color like in normal lighting.

Tested on version 1.0

**Comment by Rampastring** [comment]
To fix this we need to figure out exactly how the game ignores the color tint.

I see two ways WW could have done this:

1) Ignore the LightRedTint=, LightGreenTint= and LightBlueTint= values altogether and only apply LightIntensity

2) Make all the LightXTint values match the highest LightXTint value during an ion storm, making all light posts put out white light

**Comment by Rampastring** [comment]
Looks like the game does #2.
