### ISSUE TITLE
Feature request: Copy & paste overlays

### ISSUE THREAD

**Issue by ismail-doitbig** [CnCNet/WorldAlteringEditor#148]
![image](https://github.com/Rampastring/WorldAlteringEditor/assets/89635383/cc11865f-8f39-4f5e-b617-ced5a8efd3a6)

I'm trying to make overlays like this, i thought once i'm done with one part i could just copy and paste it, but it only copies the ground not the stones :(

If that's impossible then it would be nice to have a custom brush size so i can make long vertical/horizontal ones

**Comment by CatTanker** [comment]
You can configure what is copied in the edit drop-down, it simply defaults to the terrain only. 
![image](https://github.com/Rampastring/WorldAlteringEditor/assets/81521710/75e2d293-a899-4f24-b21c-c948b5971c86)

While this is probably no longer needed, you can define custom brush sizes in `WAE Directory/Config/BrushSizes.ini` if required.

**Comment by ismail-doitbig** [comment]
Oh awesome thanks!!
