### ISSUE TITLE
TeamTypes do not accept `House=<none>` as a valid value

### ISSUE THREAD

**Issue by Rampastring** [CnCNet/WorldAlteringEditor#160]
In YR, most teams in `aimd.ini` have `House=<none>`. This is apparently also a valid value for TeamTypes in maps in at least RA2/YR, although it is unknown whether there is any benefit to a TeamType having no owner.

Either way, WAE should be able to handle TeamTypes that have no owner. Currently WAE instead logs them as invalid.

https://discord.com/channels/338055131666972683/1064165339954425897/1240625955995910165

**Comment by Starkku** [comment]
The option was most likely added to support sharing same TeamTypes across all different countries belonging to same side, a necessity in RA2 which has more than two playable HouseTypes available in skirmish etc.

**Comment by Rampastring** [comment]
Fixed in https://github.com/Rampastring/WorldAlteringEditor/commit/3875656d88164485a94b500123fc5d131803cf7b
