### ISSUE TITLE
Multiple infantry in a cell cannot be edited

### ISSUE THREAD

**Issue by Crimsonum** [CnCNet/WorldAlteringEditor#169]
When placing multiple infantry in a cell and double-clicking them, only one of the infantry unit's properties can be edited. The rest are ignored.

For reference, FinalSun cycles through all infantry placed in a cell, allowing each one's properties to be edited in sequence.

**Comment by Rampastring** [comment]
Fixed in https://github.com/Rampastring/WorldAlteringEditor/commit/4ec20fc9a978e439a575bff05136cf927be00161

You can now double-click on the individual infantry of a cell and WAE opens specifically their properties instead of the properties of the "first" infantry on the cell.
