### ISSUE TITLE
I try to change SpriteFont to fit my language,but something went wrong.

### ISSUE THREAD

**Issue by Chai-Lu** [CnCNet/WorldAlteringEditor#182]
_Message: Text contains characters that cannot be resolved by this SpriteFont. (Parameter 'text')_

I wish using XNAContentCompiler to create SpriteFontx.xnb 

Sample
`<?xml version="1.0" encoding="utf-8"?>
<XnaContent xmlns:Graphics="Microsoft.Xna.Framework.Content.Pipeline.Graphics">
  <Asset Type="Graphics:FontDescription">
    <FontName>Arial</FontName>
    <Size>10</Size>
    <Spacing>0</Spacing>
    <UseKerning>true</UseKerning>
    <Style>Regular</Style>
    <CharacterRegions>
      <CharacterRegion>
        <Start>&#32;</Start>
        <End>&#512;</End>
      </CharacterRegion>
    </CharacterRegions>
  </Asset>
</XnaContent>`

and more larger chinese xml to test ,but it doesn`t work.

Is there any different from Client xnb file? What should I do to solve problem.

Using branch-yr for RA2 mod Edition

[except.txt](https://github.com/user-attachments/files/15942526/except.txt)

**Comment by Rampastring** [comment]
You need to specify a default character for your font. The default character is used when the application tries rendering a character that does not exist in the font.

`<DefaultCharacter>?</DefaultCharacter>`
