### ISSUE TITLE
Base node order display & reordering

### ISSUE THREAD

**Issue by Crimsonum** [CnCNet/WorldAlteringEditor#183]
Base nodes are easy to place and remove in WAE, but there is no way to tell in which order they were placed in nor is there a way to reorder them. The order of nodes is essential to AI base building, as the AI builds the structures in the exact order that the nodes were placed in; something beginner mappers are likely unaware of.

The order of nodes could be presented by numbers floating above the nodes when you're in the base nodes mode. A separate dialog would be required where you can reorder the nodes, similar to how you can reorder various scripting elements.

**Comment by Rampastring** [comment]
Implemented in https://github.com/Rampastring/WorldAlteringEditor/commit/525b5d69882729570a4b4fb17d478fda3420e3ac and https://github.com/Rampastring/WorldAlteringEditor/commit/bf7e7d3bb9d6dcd095b406064246c6b2777ec0a0
