### ISSUE TITLE
[Bug] Windows lag when dragged, allowing the cursor to grab and drag another object

### ISSUE THREAD

**Issue by Crimsonum** [CnCNet/WorldAlteringEditor#186]
When dragging a window around, it lags a bit behind the mouse cursor. If dragged fast enough, the cursor exits the window frame, and if the cursor touches another window or a map object, that object will be dragged instead. This bug means you can accidentally move objects in the map without noticing, if you're not careful when moving windows.

![GIF 7 8 2024 12 34 23](https://github.com/user-attachments/assets/319713ec-71e1-48e1-9934-5cd4fd2559fa)
Example.

**Comment by Rampastring** [comment]
This doesn't entirely resolve the issue, but should make it less bad. Windows now follow the cursor outside of the window when dragged. While less likely, it is still possible to accidentally move map objects while moving windows though.

https://github.com/Rampastring/WorldAlteringEditor/commit/1aa485722e6c02962b2c820e3009532e557e33df

**Comment by Rampastring** [comment]
This, combined with the above, should fully solve the issue of accidental dragging of objects while moving windows.

https://github.com/Rampastring/WorldAlteringEditor/commit/7fd1d5cdceb94e38385a8552642b091931ea3b23

A related issue still exists where you can accidentally place objects like units if you have the tool active while moving a window.
