### ISSUE TITLE
[Feature Request] Check usage of scripts, teams, and task forces

### ISSUE THREAD

**Issue by Crimsonum** [CnCNet/WorldAlteringEditor#192]
Trigger and local variable windows have the very useful option to check which objects (if any) a particular trigger or variable is linked to. This feature should be extended to the remaining scripting elements: teams, scripts and task forces.

**Comment by Rampastring** [comment]
This commit https://github.com/Rampastring/WorldAlteringEditor/commit/15bb7c162e828982d1967b7905a81bfe2327b031 adds this for teams and scripts through a context menu option

TaskForces will be done later.

**Comment by Rampastring** [comment]
Support for checking references of TaskForces was added in https://github.com/Rampastring/WorldAlteringEditor/commit/9518469ccd7b7cb3532ebf83362e5b07919435dd

As such, this is now fully implemented.
