### ISSUE TITLE
Support Phobos

### ISSUE THREAD

**Issue by KuroNoSeiHai** [CnCNet/WorldAlteringEditor#205]
Phobos add lots of new Events, Actions and ScriptAction. Ares index is next to YR. But Phobos index is 1000-based.

**Comment by ZivDero** [comment]
This is already possible using `IDOverride=` in the event/action's body.

**Comment by KuroNoSeiHai** [comment]
> This is already possible using `IDOverride=` in the event/action's body.

OK, Thanks
