### ISSUE TITLE
♻ Brush size removing multiple objects at once

### ISSUE THREAD

**Issue by bkmod** [CnCNet/WorldAlteringEditor#210]
Deleting and removing multiple objects at once in WAE could save me up even more time.
![image](https://github.com/user-attachments/assets/5385f764-ed00-492a-a0f6-0bcd5c1042c4)
![Objects](https://github.com/user-attachments/assets/e4569c4e-3b35-464f-b7a4-bef9e51cbd0a)

**Comment by Rampastring** [comment]
Support for brush sizes larger than 1x1 implemented in https://github.com/CnCNet/WorldAlteringEditor/commit/e8a211fdba5e90cc06138744376104eab66e5e65
