### ISSUE TITLE
HouseType Special displays black text on black background in trigger editor

### ISSUE THREAD

**Issue by ThrosturX** [CnCNet/WorldAlteringEditor#213]
HouseType Special (sometimes referred to as JP) displays as black-on-black in the trigger editor.

See accompanying image.

_Note: Untested on Windows_

![image](https://github.com/user-attachments/assets/f6fe87ea-472f-4e92-b1b8-3cb90e0b6b36)

**Comment by Rampastring** [comment]
This depended on the color given to the Special HouseType. If its color had been specified to be black, it was also displayed as black in the trigger editor.

Regardless, this should now be fixed.
