### ISSUE TITLE
Overlay Collections don't allow subsequent frames to be used or specifed?

### ISSUE THREAD

**Issue by ATHSE** [CnCNet/WorldAlteringEditor#3]
Most of my rock and debris (logs) overlays have  at least 2 frames of artwork, often the same art with a different tint, such as sandy/tan vs blue/gray, for use in different spots. I have several rock overlays that have at least 20 frames.

The collections function only uses the first frame, which makes it rather useless in my case, BUT, to be really useful, we should be able to specify not only the overlay (per line) but the frame of that overlay. This way we could include or exclude alternative tint frames for those that use them, or as an example create a collection of only the darkest rocks (frames) of each overlay.

Something like `OverlayType0=TROCK01,1` where the extra argument is frame #, but defaults to the first frame without. Frame # could start at zero or one, as long as it's clarified, but I would expect from zero.

**Comment by Rampastring** [comment]
Implemented.
