### ISSUE TITLE
[Phobos] Allow to use numeric local and global variables

### ISSUE THREAD

**Issue by MortonPL** [CnCNet/WorldAlteringEditor#32]
[Phobos introduces local/global variables with integer values instead of binary](https://phobos.readthedocs.io/en/latest/AI-Scripting-and-Mapping.html#id1). A toggle in editor configuration could be added to enable this feature in map editor as well.

**Comment by Rampastring** [comment]
Implemented in https://github.com/Rampastring/TSMapEditor/commit/93c1b7bee57bbeacab3ba6a3f3181c0fe396c398
