### ISSUE TITLE
[Bug] Large buildings have drawing artifacts

### ISSUE THREAD

**Issue by MortonPL** [CnCNet/WorldAlteringEditor#33]
Large buildings can be displayed with drawing artifacts or not displayed at all. It is yet to be determined if it's caused by foundation size or overall shape dimensions.

Example (using buildings from Mental Omega 3.3.X):
![image](https://github.com/Rampastring/TSMapEditor/assets/23420063/f9880497-fa90-446d-8af4-e7c85e6ae487)

**Comment by ATHSE** [comment]
Height doesn't seem to be a problem per se, just width. 

The problem manifests on buildings with a foundation over 5 in any direction, but the neutral hospital in RA2 (6x4) seems to display fine, while the cathedral buildings (also 6x4) are clipped.

4x4:
![image](https://github.com/Rampastring/TSMapEditor/assets/96433329/b7d8cee2-4aa1-490b-9c26-a10e71b3e726)

5x3:
![image](https://github.com/Rampastring/TSMapEditor/assets/96433329/d1d90217-f486-4973-bc15-24e5a526d0a2)

6x4:
![image](https://github.com/Rampastring/TSMapEditor/assets/96433329/d67e887f-6569-408f-9825-6fc5e4c7d4f8)
![image](https://github.com/Rampastring/TSMapEditor/assets/96433329/4e77cbe2-391a-4710-aa00-223224c856e4)
![image](https://github.com/Rampastring/TSMapEditor/assets/96433329/34ad08dd-3c97-4386-ab95-1689bb1cfd51)

**Comment by Rampastring** [comment]
Fixed by https://github.com/Rampastring/TSMapEditor/commit/67700a3c5bdee461f589d05f42e2bc883ebe714b
