### ISSUE TITLE
Too many map errors makes the error preview dialog bleed off screen, can't click OK

### ISSUE THREAD

**Issue by ATHSE** [CnCNet/WorldAlteringEditor#4]
Some scrollbars would be nice?

![image](https://user-images.githubusercontent.com/96433329/233752115-bbaad43d-99e3-49ad-b79a-9e898c57bc63.png)

**Comment by ATHSE** [comment]
A secondary problem is it auto-snaps to prevent moving it up to access the button.

**Comment by ATHSE** [comment]
Perhaps this would be best resolved by putting the errors inside a scrollable window within a larger dialog box, thus having some control over the overall default size/shape, and having the buttons always visible.

**Comment by Rampastring** [comment]
This should be fixed by https://github.com/Rampastring/TSMapEditor/commit/cde311b35f85eceeab64f7a15a24793afcbcfc91

**Comment by Rampastring** [comment]
Closing this issue, re-open if you still see it.
