### ISSUE TITLE
Dehardcode editor themes

### ISSUE THREAD

**Issue by MortonPL** [CnCNet/WorldAlteringEditor#40]
Currently there are two themes available ("Default" and "Tiberium"), neither of which is editable via INIs. It would be nice to have a system similar to that of XNA Client.

**Comment by Rampastring** [comment]
Implemented in https://github.com/Rampastring/TSMapEditor/commit/be4bf98a86d99520a29a0f9378368332df959a02 and https://github.com/Rampastring/TSMapEditor/commit/8d9ff3687604e0051fcc9c50f522808d2ec5b631
