### ISSUE TITLE
Will never find YR installation path because it is in HKEY_LOCAL_MACHINE

### ISSUE THREAD

**Issue by ZivDero** [CnCNet/WorldAlteringEditor#44]
The map editor will never find the installation path for YR because it is located in HKEY_LOCAL_MACHINE, not HKEY_CURRENT_USER

**Comment by ZivDero** [comment]
In addition, it will also never let you pass because the path in the registry points to the executable, and not just the install path, so it can't find the executable.

**Comment by Rampastring** [comment]
It can find the Yuri's Revenge installation if your YR installation includes the CnCNet client though, as the CnCNet client writes its installation directory to `HKCU\SOFTWARE\YurisRevenge`.
