### ISSUE TITLE
Add a wall painting tool

### ISSUE THREAD

**Issue by ZivDero** [CnCNet/WorldAlteringEditor#51]
Currently, it seems that the only way to paint connected overlays like walls is manually by picking the right frame. There should be a tool for this like in FA2.

**Comment by Rampastring** [comment]
You can also place walls as buildings. While they don't look connected in the map editor when you do this, the game will process them on map load and they're displayed as connected in-game.

**Comment by ATHSE** [comment]
I think there's a benefit to seeing how they look in game, especially when you "paint" the walls first and go back to selectively add damage.

There's no good reason not to have this.

Also it's worth mentioning, unless the wall is buildable it doesn't have to have a building of the same name, and in my mod at least I have removed the buildings for most of the unbuildable walls, so I couldn't even place those.
