### ISSUE TITLE
No Raise / Lower cell height upon placement hotkeys

### ISSUE THREAD

**Issue by CnCRAZER** [CnCNet/WorldAlteringEditor#94]
Within current and latest FA2SP, when selecting a cell or cliffs and hovering over the ground to place them, you can press 'Page Up / Page Down' to raise or lower the height of the cell you are about to place respectively. 

This is a huge QOL improvement.

**Comment by ZivDero** [comment]
Resolved by @Rampastring in [e967765](https://github.com/Rampastring/WorldAlteringEditor/commit/e967765bc92f5937c6a8c4ef9acba14a5541b661)
