### ISSUE TITLE
Cloaking / Gap Generating Overlay

### ISSUE THREAD

**Issue by CnCRAZER** [CnCNet/WorldAlteringEditor#95]
Add an option to enable / disable an overlay or visual representation of what's hidden with cloak generators or gap generators attached to objects when placed. 

Would be very useful for towers designated to protect survival style AI spawns to make sure things are hidden properly. 

Weapons are already parsed for their ranges, I assume would just need to add this to the parsing? But beyond my expertise.

**Comment by ZivDero** [comment]
Addressed by #112
