### ISSUE TITLE
make base nodes draggable

### ISSUE THREAD

**Issue by handama** [CnCNet/WorldAlteringEditor#97]
if simply delete and re-create base nodes, this node will be put in the last of the building list. making base nodes draggable will be convenient to adjusting bases.

**Comment by Rampastring** [comment]
I've been thinking an UI for sorting base nodes would be convenient.

**Comment by Rampastring** [comment]
Implemented in https://github.com/CnCNet/WorldAlteringEditor/commit/04af0b1a38580ae75b9e68962d5370470b9db727
